### ISSUE TITLE
Workaround IOException throwing

### ISSUE THREAD

**Issue by ByBordex** [Arquisoft/Agents_i3a#11]
When updating the kind of an Agent it is needed to throw an IOException from the domain model package which may not be a very good practice.
A possible solution may be to rethrow the IOException as other exception. However we'll need to figure out where to place this new exception and in which level it is thrown.

**Comment by ZenMaster91** [comment]
Don't worry im on it.

**Comment by ZenMaster91** [comment]
Solve it at #14
