### ISSUE TITLE
Cached version of kind

### ISSUE THREAD

**Issue by ByBordex** [Arquisoft/Agents_i3a#16]
The new implementation of kind #14  is perfect, however dealing with files any time getKind() is called may have low performance
Instead it may be done as a private access only field which updates only whenever kindCode is updated (In the constructor and in setKind() )

**Comment by ZenMaster91** [comment]
You have to ensure that if you download a user, you can get the kind, change the cvs file, get again the kind and see that kind has change. Without update anything. The system must not be aware of any change. So looking in the file is the easy and fastest way, i thing. Don't know if see any other solution that satisfies the issue, perfect. 
By the way, how much slower is ? didn't check it hehe.

**Comment by ByBordex** [comment]
I wrote a little benchmarkt, the current getKind() performs quite good but get behind the cached when looping (with high workload) thanks to the banch predictor, however this is a specific situation that will rarely appear so we migth be able to maintain the current getKind().
![7d021f63c459c0ad16d3b7ceb230110e](https://user-images.githubusercontent.com/15276132/35766910-3708d774-08e1-11e8-8093-d0978983d706.png)

**Comment by ZenMaster91** [comment]
😮 I was not expecting that hahaha. Anyway perfect, lets not worry by now for 6469ms under heavy workloads haha
