### ISSUE TITLE
Improve domain tests

### ISSUE THREAD

**Issue by ZenMaster91** [Arquisoft/Agents_i3a#20]
Improve the domain tests so we can ensure the domain works fine 100%.

**Comment by ByBordex** [comment]
According to codecov this should be the parts to check:

User: 
- toString()
- hashCode()
- equals() -> Check for object equals itself and passed parameter is null

UserInfo:
- equals()
- hashCode()
- Every setter.

UserLogin:
- Constructor with parameters.

![6cab4e1abfa536431f825691fb361623](https://user-images.githubusercontent.com/15276132/35767235-b10a5f14-08e8-11e8-8735-5fd190a54a6b.png)

**Comment by ZenMaster91** [comment]
Perfect thanks

**Comment by ByBordex** [comment]
Current status
![9fe8fb3d174a3a4450e26e2e44b9caf2](https://user-images.githubusercontent.com/15276132/35769118-8c18eaae-0906-11e8-8003-10f5d640d05f.png)

**Comment by ZenMaster91** [comment]
Current status. _I think the domain is fully tested hehe._
![captura de pantalla 2018-02-04 a las 13 27 47](https://user-images.githubusercontent.com/10364506/35777507-38df63a0-09af-11e8-97b2-f14dca1de749.png)
