### ISSUE TITLE
Change the hardcoded age to a dynamic one

### ISSUE THREAD

**Issue by ZenMaster91** [Arquisoft/Agents_i3a#3]
https://github.com/Arquisoft/Agents_i3a/blob/a568ecf996fbec7243a7b8ed5ae172f702bec44b/src/test/java/database_tests/DatabaseTest.java#L121

https://github.com/Arquisoft/Agents_i3a/blob/a568ecf996fbec7243a7b8ed5ae172f702bec44b/src/test/java/view_tests/ParticipantsDataControllerTest.java#L94

https://github.com/Arquisoft/Agents_i3a/blob/a568ecf996fbec7243a7b8ed5ae172f702bec44b/src/test/java/view_tests/ParticipantsDataControllerTest.java#L111

The 27 should be be a dynamic age. Else test will fail when actual time changes as the `.getAge()` calculates the age as `currentTime - birthday`.

**Comment by ByBordex** [comment]
Solucionado.
