### ISSUE TITLE
Clone wiki from last year.

### ISSUE THREAD

**Issue by ByBordex** [Arquisoft/Agents_i3a#35]
We should copy last year wiki pages .
[Clone wiki pages using sh](https://gist.github.com/hanxue/8488564)

**Comment by thewilly** [comment]
Naaaah maybe a reference to them its enough, don't u think?

**Comment by ByBordex** [comment]
The thing is that we probably need to change it. But yes, we can refer the older one and then add new things.

**Comment by thewilly** [comment]
Oh you mean the documentation from previous year yes. I think we can re-use their work and modify where needed. Lets start a new Issue for the new documentation.
