### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/Agents_i3a#36]
From the issue #35 we get to the point that we have to update the documentation of the project. Let's make a brain storm on how to do it.

**Comment by CarlosGarciaHdez** [comment]
From last year i think we have to change documentation refering to the installing process of mongodb, since we externalized it in issue #9

**Comment by thewilly** [comment]
okeeeeeeey, working on

**Comment by thewilly** [comment]
See #38 and mention if more documentation required

**Comment by thewilly** [comment]
@CarlosGarciaHdez update the test documentation from the readme to this son file:

```json
{
    "_id" : "58a8670df086e81dc034d7fc",
    "name" : "Clara Oswin Oswald",
    "location" : "10N10W",
    "email" : "oswald@tardis.universe",
    "kindCode" : "1",
    "id" : "45170000A",
    "password" : "khZZwjdhWwVbMdmOvz9eqBfKR1N6A+CdFBDM9c1dQduUnGewQyPRlBxB4Q6wT7Cq"
}
```
And after the JSON the update the login to the new one.
