### ISSUE TITLE
Modify REST JSON response

### ISSUE THREAD

**Issue by ByBordex** [Arquisoft/Agents_i3a#5]
Some JSON fields from the old implementations must be modified or replaced by others in order to match the new requirements.

Old JSON response:
```
{
 "firstName": Nombre, 
  "lastName": Apellidos, 
  "age": Age (will be obtained from user's birth date and current time)
  "ID": User ID, 
  "email": email 
}
```
New JSON response:
```
{
 "name": Name,
 "location": Coordinates (optional),
 "email": Email
 "id": identifier,
 "kind": agent's kind,
 "kindCode": numeric code that represents the kind,
}
```

Changes needed:
- Join firstName and lastName into a single one (name)
- Remove age field
- Add location field
- Add kind field
- Add kindCode field.

**Comment by ZenMaster91** [comment]
Notice that the kind comes from a live search in a CVS file. So if the file changes in execution time the system must be able to resolve the new changes.

**Comment by ByBordex** [comment]
Domain model now supports Location and Kind/kindcode.

Kind support is implementes as an enum type "Kind" with a "value" attribute to represent kindcode. This allow to change Kind of a user at runtime while ensuring coherence between kind and kindcode.

Details: [Commit history](https://github.com/Arquisoft/Agents_i3a/pull/6/commits)
Pull Request: [#6](https://github.com/Arquisoft/Agents_i3a/pull/6)
