### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by ByBordex** [Arquisoft/Agents_i3a#7]
The new requirements does not longer has users only as actor of the system, therefore I believe the classes should be ranamed.
Also the new specification for the master CVS is different. Therefore at the moment we have useless  attributes (Birth, nationality, ... ) on our User class so we should clean them from the sourcecode.

Proposal:
- Rename "User" to "Agent"
- Rename "UserInfo" to "AgentInfo"
- Rename "UserInfoAdapter" to "AgentInfoAdapter"
- Remove dateOfBirth, nationality and address from "User"(Agent) class

**Comment by ZenMaster91** [comment]
Nice, no problem on that.

**Comment by CarlosGarciaHdez** [comment]
Refactoring done. Also changed UserLoginInfo to AgentLoginInfo
