### ISSUE TITLE
Change the Kind uploaded in #6

### ISSUE THREAD

**Issue by ZenMaster91** [Arquisoft/Agents_i3a#8]
Notice that #6 that in theory is fix of #5 uses an enum for person entity and sensors, if tomorrow this changes in the cvs file and 1 mean cars is a problem. Fix to be completely live. Each time that is need to get a kind Code look for it in the cvs file.
Example:
```java 
public String toString() {
    ...
    "Kind" + CVSFile.getKindForCode(1); // Will return an String containing "Person".
    ...
}
```
Ensure that there is no constriction to change the hole cvs file in execution time.
So then this Kind.class does not need to exists.
https://github.com/Arquisoft/Agents_i3a/blob/2f5986eec75d2f51f1a8f32988b0b1d162971b48/src/main/java/domain/Kind.java#L3

**Comment by ByBordex** [comment]
Perhaps a static map in User class should do the trick. 
Working on it.

**Comment by ZenMaster91** [comment]
No haha you just need to store an integer in the User class that represents the kind and then look for it in the cvs file when you need the string of the code.

**Comment by ZenMaster91** [comment]
I mean, you store and int type like 1. Then when you need to know what 1 means you look in the cvs file.

**Comment by ByBordex** [comment]
@ZenMaster91 

Should work as expected now [Branch: new_response`]
(https://github.com/Arquisoft/Agents_i3a/tree/new_response)

It works fine, however I'm not very happy with throwing IOExceptions from the User class but don't know how otherwise. Have a look and then will workaround it or merge.

**Comment by ZenMaster91** [comment]
Much much better, only thing now, the format of the CSV comes from the documentation requirements. Notice the separator must be a `,` ant not a `;`. Just an small fix and ready to go. When done I will try to think about getting rid of the IOException from the model.

**Comment by ByBordex** [comment]
Done #10 

For the exception workaround a new issue has been create as under the improvement label. #11
